exclude: 'crc$'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-merge-conflict
-   repo: https://github.com/jazzband/pip-tools
    rev: 6.12.3
    hooks:
    -   id: pip-compile
        name: pip-compile luigi_pipeline/requirements.txt
        files: luigi_pipeline/pyproject.toml
        args: [--output-file=luigi_pipeline/requirements.txt, luigi_pipeline/pyproject.toml]
    -   id: pip-compile
        name: pip-compile luigi_pipeline/requirements-dev.txt
        files: luigi_pipeline/pyproject.toml
        args: [--extra=dev, --output-file=luigi_pipeline/requirements-dev.txt, luigi_pipeline/pyproject.toml]
